[[plugins]]
repository = 'Shougo/neobundle.vim'
fetch = 1

[[plugins]]
repository = 'Shougo/vimproc.vim'
    [plugins.build]
    windows = 'tools\\update-dll-mingw'
    cygwin  = 'make -f make_cygwin.mak'
    mac     = 'make -f make_mac.mak'
    unix    = 'make -f make_unix.mak'

[[plugins]]
repository = 'altercation/vim-colors-solarized'

[[plugins]]
repository = 'rhysd/accelerated-jk'

[[plugins]]
repository = 'jiangmiao/auto-pairs'

[[plugins]]
repository = 'terryma/vim-expand-region'

# text-object
## - base
[[plugins]]
repository = 'kana/vim-textobj-user'

## - underscore : a_ i_
[[plugins]]
repository = 'kana/vim-textobj-underscore'

# complete
[[plugins]]
repository = 'Shougo/neocomplete.vim'
depends    = ['Shougo/neoinclude.vim', 'Shougo/neco-syntax', 'Shougo/context_filetype.vim']
insert     = 1

[[plugins]]
repository = 'Shougo/neosnippet.vim'
depends    = ['Shougo/neosnippet-snippets', 'Shougo/context_filetype.vim']
insert     = 1
filetypes  = 'snippet'
unite_sources = ['neosnippet', 'neosnippet/user', 'neosnippet/runtime']

# Unite
[[plugins]]
repository = 'Shougo/unite.vim'
depends    = 'Shougo/neomru.vim'
    [plugins.commands]
    name     = 'Unite'
    complete = 'customlist,unite#complete_source'

[[plugins]]
repository = 'Shougo/unite-outline'

[[plugins]]
repository = 'ujihisa/unite-locate'

# File tree view
[[plugins]]
repository = 'scrooloose/nerdtree'
    [plugins.commands]
    name = 'NERDTreeToggle'

# file swap
[[plugins]]
repository = 'koara-local/next-alter.vim'
filetypes  =  ['c', 'cpp']

# COMMENT OUT
[[plugins]]
repository = 'tyru/caw.vim'
mappings = '<Plug>'

# GIT
[[plugins]]
repository = 'tpope/vim-fugitive'

[[plugins]]
repository = 'airblade/vim-gitgutter'

[[plugins]]
repository = 'rhysd/committia.vim'

[[plugins]]
repository = 'cohama/agit.vim'

# indent guide
[[plugins]]
repository = 'nathanaelkane/vim-indent-guides'

# QUICKFIX
[[plugins]]
repository = 'dannyob/quickfixstatus'

[[plugins]]
repository = 'cohama/vim-hier'

# SEARCH
[[plugins]]
repository = 'thinca/vim-visualstar'
mappings = [['x', '*'], ['x' , '#'], ['x', 'g*'], ['x', 'g#']]

[[plugins]]
repository = 'haya14busa/incsearch.vim'

# SYNTAX CHECK
#[[plugins]]
#repository = 'scrooloose/syntastic'

# STATUS LINE
[[plugins]]
repository = 'itchyny/lightline.vim'

# QuickRun
[[plugins]]
repository = 'thinca/vim-quickrun'

# C/C++
# [[plugins]]
# repository = 'justmao945/vim-clang'
# filetypes  =  ['c', 'cpp']

[[plugins]]
repository = 'vim-jp/cpp-vim'

# Go
[[plugins]]
repository = 'fatih/vim-go'

# JSON
[[plugins]]
repository = 'elzr/vim-json'
filetypes  = 'json'

# Open GL
[[plugins]]
repository = 'koara-local/opengl.vim'
lazy = 1

# wayland
[[plugins]]
repository = 'koara-local/vim-wayland'

# GLSL
[[plugins]]
repository = 'beyondmarc/glsl.vim'

# python
[[plugins]]
repository = 'davidhalter/jedi-vim'
filetypes  = 'python'
    [plugins.build]
    others = 'git submodule update --init'

# Rust
[[plugins]]
repository = 'rust-lang/rust.vim'

# Markdown
[[plugins]]
repository = 'kannokanno/previm'
filetypes  = 'markdown'

[[plugins]]
repository = 'tyru/open-browser.vim'
filetypes  = 'markdown'

[[plugins]]
repository = 'dhruvasagar/vim-table-mode'
filetypes  = 'markdown'

# TOML
[[plugins]]
repository = 'cespare/vim-toml'
filetypes  = 'toml'
